name: DevCard

on:
  # Allows to manually run this workflow from the Actions tab
  workflow_dispatch:
  push:
    branches: [ main ]
  schedule: 
    - cron: "0 0 * * *"
        
jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: Updating DevCard
        uses: dailydotdev/action-devcard@2.0.5
        with:
          devcard_id: ${{ secrets.DEVCARD_ID }}
